# Change these first
owner: keywordnew # Your GitHub organization or username, where this repository lives
repo: uptime-for-joplin # The name of this repository
user-agent: keywordnew

sites:
  - name: Joplin Cloud
    url: https://joplincloud.com
    method: GET

status-website:
  baseUrl: /uptime-for-joplin
  name: uptime for Joplin
  logoUrl: https://nilspace.xyz/content/images/size/w256h256/2023/03/icon.png
  introTitle: '(unofficial) Joplin Cloud status page'
  introMessage: 'check if Joplin Cloud is down, go to GitHub to "Watch" and get notified'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
